#!/usr/bin/env bash
# Local macOS setup: render all icon assets and app colours from assets/icon.svg.
# Requires resvg (brew install resvg), Python 3, and macOS iconutil.
set -euo pipefail
cd "$(dirname "$0")/.."

for tool in resvg python3 iconutil; do
  command -v "$tool" >/dev/null || { echo "Missing $tool. Install resvg with 'brew install resvg'; run on macOS." >&2; exit 1; }
done

work=$(mktemp -d "${TMPDIR:-/tmp}/minidiff-icons.XXXXXX")
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/MiniDiff.iconset"

# Read the semantic SVG shapes, rather than duplicating colour values in code.
python3 - "$work/icon-colors.rs" <<'PY'
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
svg = ET.parse('assets/icon.svg')
colours = {}
for name, shape_id in [('RED', 'deleted-page'), ('GREEN', 'added-page')]:
    matches = [element for element in svg.iter() if element.get('id') == shape_id]
    if len(matches) != 1 or not re.fullmatch(r'#[0-9a-fA-F]{6}', matches[0].get('fill', '')):
        sys.exit(f'assets/icon.svg needs one #{shape_id} shape with a solid #RRGGBB fill.')
    colours[name] = matches[0].get('fill')[1:].lower()
Path(sys.argv[1]).write_text(
    '// Generated by scripts/make-icons.sh from assets/icon.svg. Do not edit.\n' +
    ''.join(f'pub const {name}: u32 = 0x{value};\n' for name, value in colours.items())
)
PY

# Render every size directly from the SVG, with transparent background.
for size in 16 32 64 128 256 512 1024; do
  resvg --skip-system-fonts --width "$size" --height "$size" assets/icon.svg "$work/icon-$size.png"
done
for size in 16 32 128 256 512; do
  cp "$work/icon-$size.png" "$work/MiniDiff.iconset/icon_${size}x${size}.png"
  doubled=$((size * 2))
  cp "$work/icon-$doubled.png" "$work/MiniDiff.iconset/icon_${size}x${size}@2x.png"
done
iconutil -c icns "$work/MiniDiff.iconset" -o "$work/MiniDiff.icns"

# Install the complete set only after rendering and colour extraction succeeded.
cp "$work/icon-1024.png" assets/icon-1024.png
cp "$work/icon-256.png" assets/icon-256.png
cp "$work/icon-64.png" assets/favicon-64.png
cp "$work/MiniDiff.icns" assets/MiniDiff.icns
cp "$work/icon-colors.rs" assets/icon-colors.rs
cp "$work/icon-256.png" site/img/icon.png
cp "$work/icon-64.png" site/favicon.png
cp assets/icon.svg site/img/icon.svg
echo 'Generated app icons, macOS ICNS, website icons, and app colours from assets/icon.svg.'
